### ISSUE TITLE
Working on this

### ISSUE THREAD

**Issue by JohnLockwood** [FusionAuth/fusionauth-go-client#2]
Hi,

I have begun work on this in a Fork, here https://github.com/JohnLockwood/fusionauth-go-client.  

It's very preliminary so far but I'll be pushing updates to the fork as I do them if folks want to check progress.  The intent will be to do a pull request back here when it's more complete.  

Thanks!

**Comment by robotdan** [comment]
Thanks @JohnLockwood , we appreciate the contribution! @medhir is also working on this library, if the two of you want to discuss the work effort on this thread feel free. 

If you haven't already, review this thread : https://github.com/FusionAuth/fusionauth-issues/issues/79

In comment https://github.com/FusionAuth/fusionauth-issues/issues/79#issuecomment-472439153 I outline how we build these libraries with our client builder. 

If you want to use the client builder, there will be less work on our end to integrate it and get it published, but we appreciate any way in which you want to contribute. 

Thanks @JohnLockwood  and @medhir!

**Comment by medhir** [comment]
Hey @JohnLockwood +@robotdan. I have a fork up as well, seems like you’ve got some of the strict definitions for each response. 

My fork has a few of the REST endpoints stubbed out, though my implementation is more focused on making the API calls / http client configurabity. Each of the responses returns a generic `interface{}`, and leaves exact struct definitions to the end user. I’m planning on trying to port this to the .ftl template tonight, will let you guys know how that goes! 

Cheers

**Comment by JohnLockwood** [comment]
Hi guys,

Yes I saw it had another fork but didn't realize it had already begun.  I don't want to step on any toes here, so @medhir, if you want to run with it, that's fine.  Doing it strongly typed and adding testing etc. would have taken me some time, so I don't want to get to the end of that road and find your solution had already gotten accepted.  Enjoy.

**Comment by robotdan** [comment]
Thanks for your willingness to help @JohnLockwood.
