### ISSUE TITLE
Update README with code examples

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-go-client#5]
Fill out TODOs or delete if they do not make sense.

**Comment by robotdan** [comment]
@medhir want to take this one?

**Comment by medhir** [comment]
@robotdan, sure. I'll write up something in the next couple days. 

As to your questions: 
- `client.go` actually handles the requests. The code in that file could just be moved into `pkg/FusionAuthClient.go` 
- That commit makes sense 👍

**Comment by robotdan** [comment]
I moved the contents of `client.go` into the template to be be built into the client. Feel free to fix if I broke anything. :-)
