### ISSUE TITLE
Issues to be addressed

### ISSUE THREAD

**Issue by markschmid** [FusionAuth/fusionauth-go-client#8]
For information purposes, here's a quick rundown of the things I've discovered and that I'll try to work on in the coming days. Please let me know if there's any related input from anyone's side.

1) API Keys are not being used in this library, yet are required for most endpoints
2) There's no sufficient way to determine the "success" state of a call made to FusionAuth API. Other FusionAuth client libraries (i checked PHP and Python) attribute "success" to a response code 200-299 from FusionAuth API. Neither does this library pass through the HTTP status code.
3) ```CreateUser``` as an example for many similar occurencies: the first parameter (```userId```) is considered optional. If omitted, the FusionAuth API will create its own user ID. Yet, as is, this library does not support this optional behaviour.
4) Recently, the FusionAuth API has changed significantly, e.g. for creating tenants. It probably makes sense to introduce a Tenant struct (like the existing User struct), and maybe others.

I'm gonna try to address these things and possibly others in upcoming PRs.

**Comment by robotdan** [comment]
Thanks @markschmid 

Lots of good points. If you would like to contribute, the client is built using a template, and we can easily build the full domain using a template as well. For someone who knows Go, this should be fairly straight forward. 

See

https://github.com/FusionAuth/fusionauth-client-builder

Here is the Go template: 
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/go.client.ftl

The .NET Core example is building domain and the client, see for example:
- [netcore.client.ftl](https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/netcore.client.ftl)
- [netcore.domain.ftl](https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/netcore.domain.ftl)

**Comment by markschmid** [comment]
The recent change (https://github.com/FusionAuth/fusionauth-go-client/commit/bdb6660c58bcbcda4fe8630017bad08b4610757b) has addressed bullet number 4.
Time to close this issue, thanks.
